environment:
  nodejs_version: "7"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn mocha
  - npm install
test_script:
  - node --version
  - npm --version
  - yarn -V
  - npm test
build: off